syntax = "proto3";

package msgqueue;

option java_package = "org.thingsboard.server.common.msg.gen";
option java_outer_classname = "MsgProtos";

message TbMsgMetaDataProto {
    map<string, string> data = 1;
}

message TbMsgProto {
    string id = 1;
    string type = 2;
    string entityType = 3;
    int64 entityIdMSB = 4;
    int64 entityIdLSB = 5;
    int64 ruleChainIdMSB = 6;
    int64 ruleChainIdLSB = 7;
    int64 ruleNodeIdMSB = 8;
    int64 ruleNodeIdLSB = 9;
    int64 clusterPartition = 10;
    TbMsgMetaDataProto metaData = 11;
    int32 dataType = 13;
    string data = 14;
    int64 ts = 15;
    int64 customerIdMSB = 17;
    int64 customerIdLSB = 18;
    int64 correlationIdMSB = 20;
    int64 correlationIdLSB = 21;
    int32 partition = 22;
}
